add_newline = false

[character]
error_symbol = "[X](bold red) "
# Prompt format
format = """
[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€](bold fg:#CC99CC)
[â”‚](bold fg:#CC99CC)$directory$rust$package
[â””â”€>](bold fg:#CC99CC) """

[username]
style_user = "bold fg:#CC99CC"
style_root = "white bold"
format = " [$user@]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[$hostname](bold fg:#CC99CC): "
disabled = false

[directory]
read_only = "ğŸ”’"
read_only_style= "bold white"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[cmd_duration]
disabled = true
